// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_d0Jc3s5PautxQEA8dQuNpXUmEwKvN4',
    appId: '1:475067046837:web:adc8bfa3d1ac68497a97fc',
    messagingSenderId: '475067046837',
    projectId: 'twin-handyman',
    authDomain: 'twin-handyman.firebaseapp.com',
    storageBucket: 'twin-handyman.firebasestorage.app',
    measurementId: 'G-K8F7PWJXCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAGUfAWGmnf696dZDcBTglzF0VWkflyk',
    appId: '1:475067046837:android:73e495bb62746e3b7a97fc',
    messagingSenderId: '475067046837',
    projectId: 'twin-handyman',
    storageBucket: 'twin-handyman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhIPtFzcQPTgFTjd2XnSG5ZBflJ-jyr8',
    appId: '1:475067046837:ios:105aca3ecadbd9f27a97fc',
    messagingSenderId: '475067046837',
    projectId: 'twin-handyman',
    storageBucket: 'twin-handyman.firebasestorage.app',
    iosBundleId: 'com.rameezkayanitwinshandyman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhIPtFzcQPTgFTjd2XnSG5ZBflJ-jyr8',
    appId: '1:475067046837:ios:e29777ec43a407517a97fc',
    messagingSenderId: '475067046837',
    projectId: 'twin-handyman',
    storageBucket: 'twin-handyman.firebasestorage.app',
    iosBundleId: 'com.example.twin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV_d0Jc3s5PautxQEA8dQuNpXUmEwKvN4',
    appId: '1:475067046837:web:b5a4a82208b3c5f47a97fc',
    messagingSenderId: '475067046837',
    projectId: 'twin-handyman',
    authDomain: 'twin-handyman.firebaseapp.com',
    storageBucket: 'twin-handyman.firebasestorage.app',
    measurementId: 'G-Q4XDETF0T3',
  );
}
